/**
 * Vercel build step (Build Command: npm run website:config).
 * Prefers env vars when set; otherwise keeps committed assets/js/config.js.
 */
const fs = require('fs');
const path = require('path');

const out = path.join(__dirname, 'assets', 'js', 'config.js');

function env(key) {
  return (process.env[key] || '').trim();
}

const paddleClientToken =
  env('VITE_PADDLE_CLIENT_TOKEN') || env('PADDLE_CLIENT_TOKEN');
const supabaseUrl = env('VITE_SUPABASE_URL') || env('SUPABASE_URL');
const supabaseAnonKey = env('VITE_SUPABASE_ANON_KEY') || env('SUPABASE_ANON_KEY');

if (fs.existsSync(out) && !paddleClientToken && !supabaseUrl) {
  console.log('[website:config] Using committed assets/js/config.js');
  process.exit(0);
}

let existing = {};
if (fs.existsSync(out)) {
  try {
    const raw = fs.readFileSync(out, 'utf8');
    const m = raw.match(/window\.FLOW_SITE_CONFIG\s*=\s*(\{[\s\S]*\});?\s*$/);
    if (m) existing = JSON.parse(m[1]);
  } catch (_) {
    /* ignore parse errors; rewrite from env */
  }
}

const config = {
  supabaseUrl: supabaseUrl || existing.supabaseUrl || '',
  supabaseAnonKey: supabaseAnonKey || existing.supabaseAnonKey || '',
  paddleClientToken: paddleClientToken || existing.paddleClientToken || '',
  pricing: existing.pricing || undefined,
  paddlePriceIds: {
    pro: {
      monthly:
        env('VITE_PADDLE_PRO_MONTHLY_PRICE_ID') ||
        env('VITE_PADDLE_MONTHLY_PRICE_ID') ||
        existing.paddlePriceIds?.pro?.monthly ||
        '',
      annual:
        env('VITE_PADDLE_PRO_ANNUAL_PRICE_ID') ||
        env('VITE_PADDLE_ANNUAL_PRICE_ID') ||
        existing.paddlePriceIds?.pro?.annual ||
        '',
    },
    pro_max: {
      monthly:
        env('VITE_PADDLE_PROMAX_MONTHLY_PRICE_ID') ||
        env('VITE_PADDLE_PRO_MAX_MONTHLY_PRICE_ID') ||
        existing.paddlePriceIds?.pro_max?.monthly ||
        '',
      annual:
        env('VITE_PADDLE_PROMAX_ANNUAL_PRICE_ID') ||
        env('VITE_PADDLE_PRO_MAX_ANNUAL_PRICE_ID') ||
        existing.paddlePriceIds?.pro_max?.annual ||
        '',
    },
  },
};

if (!config.paddleClientToken) {
  console.error(
    '[website:config] Missing paddleClientToken. Commit assets/js/config.js or set VITE_PADDLE_CLIENT_TOKEN on Vercel.',
  );
  process.exit(1);
}

fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(
  out,
  `/** Generated by website/ensure-config.js */\nwindow.FLOW_SITE_CONFIG = ${JSON.stringify(config, null, 2)};\n`,
  'utf8',
);
console.log('[website:config] Wrote assets/js/config.js');
